#█▀▀█ █░░█ █▀▀ ▀▀█ █░░ █░░█ ░ █▀▀▄ █▀▀ ▀▀█▀▀
#█░░█ █░░█ █▀▀ ▄▀░ █░░ █▄▄█ ▄ █░░█ █▀▀ ░░█░░
#▀▀▀█ ░▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀ ▄▄▄█ █ ▀░░▀ ▀▀▀ ░░▀░░

# Discord: erisos



#İzin verilen komutlar
allow_commands:
  - /qSystem #Çakma lobi de etraf da düzenleme yapılacağı zaman efektleri kaldırma komutu.
  - /qDefaultPlayerEffect
  - /qSpawn
  - /login
  - /register

join_screen_text: true
big_screen_text: '&3Hoşgeldin'
small_screen_text: '&f/bilgi yazarak sunucu hakkında bilgi alabilirsin!'

error_message: '&eBu işlemi gerçekleştirmek için yetkin bulunmuyor.'
error_message_chat: '&eSohbette konuşmak için &fDEMIR &eveya daha üst bir rütbeye sahip olman gerekir.'

# RANDOM SETTINGS
pvp: true

# Player jump disable
set_jump_block: false

# Set walk speed 0
set_walk_speed: false

# Set fly speed 0
set_fly_speed: false

set_gamemode: ADVENTURE
set_invisibility_effect: false
on_exit_reset: false




# If the player falls into a gap, they are teleported to the spawn location.
fall_void_teleport_to_spawn: true

# Start at the spawn location when the player joins the server.
# WARN!(It only teleports players who have entered the game before to the spawn location.)
join_teleport_spawn: true

# Players entering the server for the first time start from the spawn location.
firstjoin_teleport_spawn: true

# Dead players start from the spawn location.
respawn_teleport_spawn: true

# SPAWN SYSTEM MESSAGES
setspawn_message: '&aDoğma bloğu başarılı bir şekilde ayarlandı.'
error_setspawn_message: '&cDoğma noktası ayarlanamadı!'
notspawn_message: '&cDoğma noktası ayarlanmamış!'



