#█▀▀█ █░░█ █▀▀ ▀▀█ █░░ █░░█ ░ █▀▀▄ █▀▀ ▀▀█▀▀
#█░░█ █░░█ █▀▀ ▄▀░ █░░ █▄▄█ ▄ █░░█ █▀▀ ░░█░░
#▀▀▀█ ░▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀ ▄▄▄█ █ ▀░░▀ ▀▀▀ ░░▀░░

# Discord: erisos


error_message: "&eYou do not have the authority to carry out this operation."
error_message_chat: "&eTo speak in the chat you need to have the rank &fVIP &eor higher."
discord_link: "&9https://discord.gg/q4EKuxAvRt"

#allowed commands
allow_commands:
  - /örs
  - /qSetSpawn
  - /spawn
  - /login
  - /register


#Title to send when using a command not in the list
not_allowed_command_send_title: true
not_allowed_command_big_title: "What are you trying to do?!"
not_allowed_command_small_title: "I guess you're the only smart one..."


#Turns off players' login and logout messages. #BETA #BETA #BETA #BETA
join_leave_message_disable: true


join_title:
  join_send_title: true
  title_send_after_seconds: 3
  join_big_title: "&3Welcome"
  join_small_title: "&fYou can get information about the server by typing /help"


#BETA #BETA #BETA
bad_words_blocker:
  #true prevents the player from sending messages if one of the words in the "bad_words" list appears in the player"s messages.
  swear_blocker: true

  bad_alert_big_title: "&cRude Human!!"
  bad_alert_small_title: ""

  bad_words:
    - fuck
    - mom


spawn:
  # If the player falls into a gap, they are teleported to the spawn location.
  fall_void_teleport_to_spawn: true

  # Start at the spawn location when the player joins the server.
  # WARN!(It only teleports players who have entered the game before to the spawn location.)
  join_teleport_spawn: true

  # Players entering the server for the first time start from the spawn location.
  firstjoin_teleport_spawn: true

  # Dead players start from the spawn location.
  respawn_teleport_spawn: true

  # Spawn System Messages
  setspawn_message: "&aThe spawn block has been successfully set."
  error_setspawn_message: "&cFailed to set the spawn location!"
  notspawn_message: "&cSpawn location is not set."
  teleport_spawn_message: "&aYou have successfully teleported to your spawn point!"

interactive_blocks:
  disable_blocks_send_message: true
  disable_blocks_message: "&cYou cannot access this block!"
  disable_blocks: false
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  block_list:
    - WORKBENCH

blocks:
  disable_block_placement: false
  disable_block_break: false
  disable_block_placement_message: "&cYou cannot placement a block!"
  disable_block_break_message: "&cYou cannot break a block!"

mob_settings:
  # If you set true, no creature will spawn above the barrier block.
  barrier_block_mob_spawn_disable: true


time_loop: false
time_loops:
  '1':
    hour: 12
    minutes: 00
    commands:
      - "/kick erisos"
    message: "Erisos kick."
    # Sends messages only to players with permission. Leave blank if you don't want this.
    message_perm: test.message
  '2':
    hour: 13
    minutes: 00
    commands:
      - "/kick erisos"
    message: "Erisos kick."
    # Sends messages only to players with permission. Leave blank if you don't want this.
    message_perm: timeloop.2.message



