name: qSystem
version: '1.2.2'
main: me.erisos.qsystem.QSystem
commands:
  qSetSpawn:
    description: setspawn
  spawn:
    description: spawn
  qDefaultPlayerEffect:
    description: player effect reload