name: qSystem
version: '1.2.4'
main: me.erisos.qsystem.QSystem
commands:
  qSetSpawn:
    description: setspawn
  spawn:
    description: spawn
  qDefaultPlayerEffect:
    description: player effect reload
  discord:
    description: send a discord link to a player
  örs:
    description: player open anvil
  zırhtasarım:
    description: player open smihting table