name: qCore
version: '1.2.5'
main: me.erisos.qsystem.QSystem
commands:
  qSetSpawn:
    description: setspawn
  spawn:
    description: spawn
  qDefaultPlayerEffect:
    description: player effect reload
  discord:
    description: send a discord link to a player
  zırhtasarım:
    description: player open smihting table